### ISSUE TITLE
ros2_console dependency

### ISSUE THREAD

**Issue by Peter9606** [bponsler/message_filters#2]
Since there's no way to raise issue in your forked ros_comm project, I just put my question here.
While I was doing this [PR](https://github.com/bponsler/ros_comm/pull/1), I found new ros_comm has a dependency on your new created ros2_console.  So in order to push this ros_comm back to ros2 repo and let it be accepted by community, you should first make ros2_console be accepted, right?
I'm a rookie on opensource, and just wonder is it a risk?

**Comment by bponsler** [comment]
BTW -- I just updated the other repository to allow issues, so you can create them there in the future.

I only created ros2_console as a temporary way to make porting packages easier until there was a console logging mechanism in ROS 2. At the time there wasn't a mechanism, but [one](http://docs.ros2.org/beta2/api/rcutils/index.html) was included in the [R2B2](https://github.com/ros2/ros2/wiki/Beta2-Overview) release.

We'll just need to replace the ros2_console uses with rcutils which is pretty minor.

**Comment by Peter9606** [comment]
Gotcha. Thank you!
I'll handle this if it's not fixed yet next time I come back :-)

**Comment by bponsler** [comment]
It was very simple to remove, so I went ahead and removed the dependency :)

See: [this commit](https://github.com/bponsler/ros_comm/commit/9243c7700cffd6ef3fe77e7ec96971e01d8ed444)

Closing this issue

**Comment by Peter9606** [comment]
Great!
